### ISSUE TITLE
🐛 Music files and playlist are not showing

### ISSUE THREAD

**Issue by Kavyansh-Bagdi** [Rishabh050803/soptify#1]
![image](https://github.com/Rishabh050803/soptify/assets/153486713/15e6b812-d8ba-4e1a-afad-ba7ad35d9fff)

**Comment by Rishabh050803** [comment]
Try this
https://soptifylevel0.freewebhostmost.com/

**Comment by Kavyansh-Bagdi** [comment]
why these are not loading in github page ?
